python main.py --task lap14 --train_dataset_path lap14/train --dev_dataset_path lap14/dev --test_dataset_path lap14/test --model_name_or_path t5-base --do_train --do_eval --train_batch_size 2 --gradient_accumulation_steps 2 --eval_batch_size 16 --learning_rate 3e-4 --num_train_epochs 20 --regressor True --use_tagger True --beta 0.1 --model_weights models/model_after6epochs  --logger_name lap14_logs_regressor0.1_and_tagger_with_contrast6.txt  --log_message epoch6_2_2_3e4_0.1default --gpu_id 1 

python main.py --task lap14 --train_dataset_path lap14/train --dev_dataset_path lap14/dev --test_dataset_path lap14/test --model_name_or_path t5-base --do_train --do_eval --train_batch_size 2 --gradient_accumulation_steps 2 --eval_batch_size 16 --learning_rate 3e-4 --num_train_epochs 20 --regressor True --use_tagger True --beta 0.1 --model_weights models/model_after8epochs  --logger_name lap14_logs_regressor0.1_and_tagger_with_contrast8.txt  --log_message epoch8_2_2_3e4_0.1default --gpu_id 1 

python main.py --task lap14 --train_dataset_path lap14/train --dev_dataset_path lap14/dev --test_dataset_path lap14/test --model_name_or_path t5-base --do_train --do_eval --train_batch_size 2 --gradient_accumulation_steps 2 --eval_batch_size 16 --learning_rate 3e-4 --num_train_epochs 20 --regressor True --use_tagger True --beta 0.1 --model_weights models/model_after9epochs  --logger_name lap14_logs_regressor0.1_and_tagger_with_contrast9.txt  --log_message epoch9_2_2_3e4_0.1default --gpu_id 1

python main.py --task lap14 --train_dataset_path lap14/train --dev_dataset_path lap14/dev --test_dataset_path lap14/test --model_name_or_path t5-base --do_train --do_eval --train_batch_size 2 --gradient_accumulation_steps 2 --eval_batch_size 16 --learning_rate 3e-4 --num_train_epochs 20 --regressor True --use_tagger True --beta 0.1 --model_weights models/model_after10epochs  --logger_name lap14_logs_regressor0.1_and_tagger_with_contrast10.txt  --log_message epoch10_2_2_3e4_0.1default --gpu_id 1 

python main.py --task lap14 --train_dataset_path lap14/train --dev_dataset_path lap14/dev --test_dataset_path lap14/test --model_name_or_path t5-base --do_train --do_eval --train_batch_size 2 --gradient_accumulation_steps 2 --eval_batch_size 16 --learning_rate 3e-4 --num_train_epochs 20 --regressor True --use_tagger True --beta 0.1 --model_weights models/model_after12epochs  --logger_name lap14_logs_regressor0.1_and_tagger_with_contrast12.txt  --log_message epoch12_2_2_3e4_0.1default --gpu_id 1 

python main.py --task lap14 --train_dataset_path lap14/train --dev_dataset_path lap14/dev --test_dataset_path lap14/test --model_name_or_path t5-base --do_train --do_eval --train_batch_size 2 --gradient_accumulation_steps 2 --eval_batch_size 16 --learning_rate 3e-4 --num_train_epochs 20 --regressor True --use_tagger True --beta 0.1 --model_weights models/model_after14epochs  --logger_name lap14_logs_regressor0.1_and_tagger_with_contrast14.txt  --log_message epoch14_2_2_3e4_0.1default --gpu_id 1 